services:
  sensor:
    build: .
    container_name: sensor
    privileged: true  # Necess치rio para acessar os pinos GPIO
    deploy:
#      replicas: 2  # Para executar em dois n칩s do cluster
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
    environment:
      - SENSOR_PIN=17  # GPIO do sensor
    depends_on:
      - mqtt-broker

  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    deploy:
      placement:
        constraints:
          - node.role == manager  # O broker ser치 executado apenas no n칩 principal
