version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      RABBITMQ_HOST: host.docker.internal
      RABBITMQ_QUEUE: sensor_data_queue
    depends_on:
      - rabbitmq
      - mongo

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: fazenda
      RABBITMQ_DEFAULT_PASS: steffenthanos2020

  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: maidai
      MONGO_INITDB_ROOT_PASSWORD: 123maidai456
    ports:
      - "27017:27017"
